/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frm;

import modelo.ConsultaInfoPago;
import modelo.ControTrabajadores;
import modelo.InfoPago;
import modelo.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author reyna
 */
public class FormPago extends javax.swing.JFrame {

    private static InfoPago mod;
    private static ConsultaInfoPago modC;
    public static DefaultTableModel modelTable;
    public static ResultSet registro;
    public static ControTrabajadores conn;

    /**
     * Creates new form FormPago
     */

    public FormPago() {
        initComponents();

        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("YYYY-MM-dd");

        //CAMPOS DE TEXTO MODIFICACION
        tlineFecha.setText(formatoFecha.format(fecha));
        tlineFecha.setEditable(true);
        tlineIdEmpelado.setEditable(false);
        tlineId.setEditable(false);

        //METODOS INICIALES
        Mostrar();
        recargar();

    }

    public void Mostrar() {

        try {

            DefaultTableModel modelo = new DefaultTableModel();
            TablaPago.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con = conn.Conectar();

            String sql = "SELECT * FROM infopago";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("ID");
            modelo.addColumn("ID_empleado");
            modelo.addColumn("fecha");
            modelo.addColumn("unidad");
            modelo.addColumn("descuento");
            modelo.addColumn("total");

            while (rs.next()) {

                Object[] filas = new Object[cantidadColumnas];

                for (int i = 0; i < cantidadColumnas; i++) {

                    filas[i] = rs.getObject(i + 1);

                }

                modelo.addRow(filas);

            }

        } catch (Exception e) {

            System.err.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tlineIdEmpelado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tlineUnidad = new javax.swing.JTextField();
        tlineDescuento = new javax.swing.JTextField();
        tlineTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleado = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tlineFecha = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        tlineId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPago = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tlineIdEmpelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlineIdEmpeladoActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Empleado");

        jLabel2.setText("Unidades");

        jLabel3.setText("Descuento");

        jLabel4.setText("Total dia");

        tlineUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlineUnidadActionPerformed(evt);
            }
        });
        tlineUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tlineUnidadKeyReleased(evt);
            }
        });

        tlineTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlineTotalActionPerformed(evt);
            }
        });

        TablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "nombre", "dui", "cargo"
            }
        ));
        TablaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaEmpleado);

        jLabel5.setText("Fecha");

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("Empleados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnInsertar)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tlineTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tlineFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tlineId, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tlineIdEmpelado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tlineDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tlineUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(237, 237, 237)))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tlineUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tlineDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tlineTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tlineFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tlineId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tlineIdEmpelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        TablaPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "id_Empelado", "fecha", "unidades", "descuento", "total_dia"
            }
        ));
        TablaPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPagoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaPago);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("PAGO POR DIA");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setText("Tabla Pago por dia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(382, 382, 382))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tlineIdEmpeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlineIdEmpeladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlineIdEmpeladoActionPerformed

    private void tlineUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlineUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlineUnidadActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:

        mod = new InfoPago();
        modC = new ConsultaInfoPago();

        if (tlineIdEmpelado.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "debe seleccionar un empleado para el pago de este dia");

        } else {

            if (tlineUnidad.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "El campo de Unidades no debe estar vacio");

            } else {

                mod.setId_Empleado(tlineIdEmpelado.getText());
                mod.setFecha(java.sql.Date.valueOf(tlineFecha.getText()));
                mod.setUnidades(Integer.parseInt(tlineUnidad.getText()));
                mod.setDescuento(Double.parseDouble(tlineDescuento.getText()));
                mod.setTotal_dia(Double.parseDouble(tlineTotal.getText()));

                if (modC.registrar(mod)) {

                    JOptionPane.showMessageDialog(null, "Registro Guardado");
                    Limpiar();
                    Mostrar();
                } else {

                    JOptionPane.showMessageDialog(null, "Error al guardar el Registro");

                }

            }

        }


    }//GEN-LAST:event_btnInsertarActionPerformed

    private void tlineTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlineTotalActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_tlineTotalActionPerformed

    //METODO PARA CALCULAR LA GANACIA, DESCUENTOS DE CADA EMPLEADO
    private void tlineUnidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tlineUnidadKeyReleased
        // TODO add your handling code here:

        double salarioFijo = 8.00;
        int uni = Integer.parseInt(tlineUnidad.getText());
        double descuento = 0;
        double aumento = 0;
        double total = 0;
        /*
        p.setId_Empleado(tlineIdEmpelado.getText());
        p.setUnidades(Integer.parseInt(tlineUnidad.getText()));*/

        if (uni == 20) {

            total = 8.00;
            tlineDescuento.setText(String.valueOf(descuento));

        } else if (uni > 20) {

            for (int i = 20; i < uni; i++) {

                aumento = aumento + 0.20;

            }

            tlineDescuento.setText(String.valueOf(descuento));
            total = salarioFijo + aumento;

        } else if (uni > 0 && uni < 20) {

            for (int i = 0; i < 20 - uni; i++) {

                descuento = descuento + 0.25;

            }
            tlineDescuento.setText(String.valueOf(descuento));
            total = salarioFijo - descuento;

        } else {

            total = 0;
        }

        tlineTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_tlineUnidadKeyReleased

    private void TablaEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEmpleadoMouseClicked
        // TODO add your handling code here:

        TableModel model = TablaEmpleado.getModel();
        tlineIdEmpelado.setText("" + model.getValueAt(TablaEmpleado.getSelectedRow(), 0));


    }//GEN-LAST:event_TablaEmpleadoMouseClicked

    private void TablaPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPagoMouseClicked
        // TODO add your handling code here:
        
        TableModel model = TablaPago.getModel();
        tlineId.setText(""+model.getValueAt(TablaPago.getSelectedRow(), 0));
        tlineIdEmpelado.setText(""+model.getValueAt(TablaPago.getSelectedRow(), 1));
        tlineUnidad.setText(""+model.getValueAt(TablaPago.getSelectedRow(), 3));
        tlineDescuento.setText(""+model.getValueAt(TablaPago.getSelectedRow(), 4));
        tlineTotal.setText(""+model.getValueAt(TablaPago.getSelectedRow(), 5));
        
    }//GEN-LAST:event_TablaPagoMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        //Procedimiento
        
        mod = new InfoPago();
        modC = new ConsultaInfoPago();

        if(tlineId.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Por favor seleccione el registro que desea modificar de la tabla de Pagos");
        
        
        }else{
            
            
            if (tlineIdEmpelado.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "debe seleccionar un empleado para el pago de este dia");

        } else {

            if (tlineUnidad.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "El campo de Unidades no debe estar vacio");

            } else {
                
                mod.setId_Empleado(tlineIdEmpelado.getText());
                mod.setFecha(java.sql.Date.valueOf(tlineFecha.getText()));
                mod.setUnidades(Integer.parseInt(tlineUnidad.getText()));
                mod.setDescuento(Double.parseDouble(tlineDescuento.getText()));
                mod.setTotal_dia(Double.parseDouble(tlineTotal.getText()));
                mod.setId(Integer.parseInt(tlineId.getText()));

                if (modC.modificar(mod)) {

                    JOptionPane.showMessageDialog(null, "Registro Modificado");
                    Limpiar();
                    Mostrar();
                } else {

                    JOptionPane.showMessageDialog(null, "Error Modificar el registro");

                }

            }

        }
        
       }
        
        
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
         mod = new InfoPago();
        modC = new ConsultaInfoPago();
    
                
                

                
                if(tlineId.getText().isEmpty()){
                
                JOptionPane.showMessageDialog(null, "Por favor seleccione el registro que desea ELIMINAR de la tabla de Pagos");
                
                }else{
                
                    mod.setId(Integer.parseInt(tlineId.getText()));
                    
                 if (modC.eliminar(mod)) {

                    JOptionPane.showMessageDialog(null, "Registro Eliminado");
                    Limpiar();
                    Mostrar();
                } else {

                    JOptionPane.showMessageDialog(null, "Error al eliminar el registro");

                }
                
                }
                
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menufrm m = new Menufrm();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Limpiar() {

        tlineDescuento.setText("");
        tlineIdEmpelado.setText("");
        tlineTotal.setText("");
        tlineUnidad.setText("");
        tlineId.setText("");

    }

    public void recargar() {
        //creando la instancia de la clase
        conn = new ControTrabajadores();
        modelTable = new DefaultTableModel();
        TablaEmpleado.setModel(modelTable);

        registro = conn.Cargar();
        modelTable.addColumn("ID");
        modelTable.addColumn("Nombre");
        modelTable.addColumn("DUI");
        modelTable.addColumn("Cargo");
        modelTable.addColumn("direccion");
        modelTable.addColumn("Telefono");
        modelTable.addColumn("Fecha");
        Object[] data = new Object[6];

        try {
            while (registro.next()) {
                for (int i = 0; i < 6; i++) {

                    data[i] = registro.getObject(i + 1);
                }
                modelTable.addRow(data);

            }
        } catch (SQLException ex) {
            Logger.getLogger(FormPago.class.getName()).log(Level.SEVERE, null, ex);
        }

        conn.cerrarConexion();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaEmpleado;
    private javax.swing.JTable TablaPago;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tlineDescuento;
    private javax.swing.JTextField tlineFecha;
    private javax.swing.JTextField tlineId;
    private javax.swing.JTextField tlineIdEmpelado;
    private javax.swing.JTextField tlineTotal;
    private javax.swing.JTextField tlineUnidad;
    // End of variables declaration//GEN-END:variables

    private String toString(double total) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
