/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frm;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import modelo.Conexion;

/**
 *
 * @author reyna
 */
public class FormInformes extends javax.swing.JFrame {

    /**
     * Creates new form FormInformes
     */
    public FormInformes() {
        initComponents();
        
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("YYYY-MM-dd");

        //CAMPOS DE TEXTO MODIFICACION
        tlineFecha.setText(formatoFecha.format(fecha));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tlineFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reporte.png"))); // NOI18N
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setText("Generar informe planilla de pago");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setText("Generar ficha de Empleados");

        jLabel5.setText("Fecha final de mes:");

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reporte.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(btnEmpleados)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tlineFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel12)
                    .addContainerGap(418, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel11)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tlineFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEmpleados)
                        .addGap(108, 108, 108))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(jLabel12)
                    .addContainerGap(279, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menufrm m = new Menufrm();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
        
         
        
         if(tlineFecha.getText().isEmpty()){
         
         JOptionPane.showMessageDialog(null, "Ingrese la fecha final de mes de la planilla");
         
         }else{
         
          try {
              Date fecha = java.sql.Date.valueOf(tlineFecha.getText());
               Document documento = new Document();
        
           
           File home = FileSystemView.getFileSystemView().getHomeDirectory();
           String absPath = home.getAbsolutePath();
           PdfWriter.getInstance(documento, new FileOutputStream(absPath +"\\Planilla.pdf"));
           
           
           
            documento.open();
            
             Paragraph para = new Paragraph("Planilla de Pago "+fecha+" \n\n\n");
             documento.add(para);
            
            PdfPTable tabla = new PdfPTable(6);
                    
                    
                    tabla.addCell("Nombre");
                    tabla.addCell("Salario Base");
                    tabla.addCell("ISSS");
                    tabla.addCell("AFP");
                    tabla.addCell("FECHA PAGO");
                    tabla.addCell("SALARIO TOTAL");
                    
                    
                    try {
                        
                        
                        
                        Conexion conn = new Conexion();
                        Connection con = conn.Conectar();
                        PreparedStatement pst = con.prepareStatement("SELECT nombre,salario_base,isss,afp,fecha_pago,salario_total FROM pagoempleados where fecha_pago='"+fecha+"'");
                        
                        ResultSet rs = pst.executeQuery();
                        
                        
                        if(rs.next()){
                        
                            do{
                                
                                
                                tabla.addCell(rs.getString(1));
                                tabla.addCell(rs.getString(2));
                                tabla.addCell(rs.getString(3));
                                tabla.addCell(rs.getString(4));
                                tabla.addCell(rs.getString(5));
                                tabla.addCell(rs.getString(6));
                                
                            
                            }while(rs.next());
                                    
                                    documento.add(tabla);
                        
                        }else{
                        
                        
                        }
                
            } catch (DocumentException | SQLException e) {
            }
                    
             documento.close();
            JOptionPane.showMessageDialog(null, "Informe creado en el Escritorio de la Computadora");
            
        } catch (DocumentException | HeadlessException | FileNotFoundException e) {
        }
         
         
         }
        
       
        
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        Document document = new Document();
        
        
        try {
           /* 
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream("D:\\Documentos\\reporte.pdf"));
            
            */
           
           File home = FileSystemView.getFileSystemView().getHomeDirectory();
           String absPath = home.getAbsolutePath();
           PdfWriter.getInstance(document, new FileOutputStream(absPath +"\\Ficha_Empleados.pdf"));
           
           
           
            document.open();
            
             Paragraph para = new Paragraph("FICHA DE EMPLEADOS\n\n\n");
             document.add(para);
            
            PdfPTable tabla = new PdfPTable(7);
                    
                    tabla.addCell("Id Empleado");
                    tabla.addCell("Nombre");
                    tabla.addCell("DUI");
                    tabla.addCell("Cargo");
                    tabla.addCell("Direccion");
                    tabla.addCell("Telefono");
                    tabla.addCell("Fecha Contratacion");
                    
                    
                    try {
                        
                        Conexion conn = new Conexion();
                        Connection con = conn.Conectar();
                        PreparedStatement pst = con.prepareStatement("SELECT * FROM empleados");
                        
                        ResultSet rs = pst.executeQuery();
                        
                        
                        if(rs.next()){
                        
                            do{
                                
                                tabla.addCell(rs.getString("id_empleado"));
                                tabla.addCell(rs.getString("nombre"));
                                tabla.addCell(rs.getString("dui"));
                                tabla.addCell(rs.getString("cargo"));
                                tabla.addCell(rs.getString("direccion"));
                                tabla.addCell(rs.getString("telefono"));
                                tabla.addCell(rs.getString("fecha_contratacion"));
                                
                            
                            }while(rs.next());
                                    
                                    document.add(tabla);
                        
                        }else{
                        
                        
                        }
                
            } catch (DocumentException | SQLException e) {
            }
                    
             document.close();
            JOptionPane.showMessageDialog(null, "Informe creado en el Escritorio de la Computadora");
            
        } catch (DocumentException | HeadlessException | FileNotFoundException e) {
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInformes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tlineFecha;
    // End of variables declaration//GEN-END:variables
}
